[dependencies.core]
stage = 0
git = "https://github.com/MegatonHammer/rust"

[dependencies.std_unicode]
stage = 1
git = "https://github.com/MegatonHammer/rust"

[dependencies.alloc]
stage = 2
git = "https://github.com/MegatonHammer/rust"

[dependencies.std]
stage = 3
git = "https://github.com/MegatonHammer/rust"
