[dependencies.core]
stage = 0
git = "https://github.com/megatonhammer/rust"

[dependencies.compiler_builtins]
stage = 1
git = "https://github.com/megatonhammer/rust"
features = ["mem"]

[dependencies.alloc]
stage = 2
git = "https://github.com/megatonhammer/rust"

[dependencies.std]
stage = 3
git = "https://github.com/megatonhammer/rust"
features = ["panic-unwind"]
