[dependencies.core]
stage = 0
path = "../rust/src/libcore"

[dependencies.compiler_builtins]
stage = 1
path = "../rust/src/libcompiler_builtins"
features = ["mem"]

[dependencies.alloc]
stage = 2
path = "../rust/src/liballoc"

[dependencies.std]
stage = 3
path = "../rust/src/libstd"
