pub mod detail;
pub type ExternalApplicationCatalogId = u128;
pub type ExternalApplicationCatalog = ();
pub type InAppScreenName = ();
pub type MiiName = [u8; 0x20];
pub type FriendCode = [u8; 0x20];
pub type NintendoNetworkIdUserInfo = ();
pub type PlayHistoryStatistics = u128;
pub type Url = [u8; 0xa0];
pub type Relationship = u64;
pub type FacedFriendRequestRegistrationKey = [u8; 0x40];
pub type RequestId = u64;
pub type MiiImageUrlParam = u128;
pub type PlayHistoryRegistrationKey = ();
pub type ApplicationInfo = u128;
