mod impl_i_session;
pub use self::impl_i_session::*;
mod impl_i_system_manager;
pub use self::impl_i_system_manager::*;
mod impl_i_manager_privileged;
pub use self::impl_i_manager_privileged::*;
mod impl_i_manager;
pub use self::impl_i_manager::*;
pub type PerformanceMode = u32;
pub type EventTarget = u32;
pub type PerformanceConfiguration = u32;
pub type ThrottlingState = [u8; 0x28];
