pub mod http;
mod impl_i_account_service_for_system_service;
pub use self::impl_i_account_service_for_system_service::*;
pub mod baas;
pub mod profile;
mod impl_i_account_service_for_administrator;
pub use self::impl_i_account_service_for_administrator::*;
mod impl_i_account_service_for_application;
pub use self::impl_i_account_service_for_application::*;
pub mod nas;
pub mod detail;
mod impl_i_baas_access_token_accessor;
pub use self::impl_i_baas_access_token_accessor::*;
pub type NintendoAccountAuthorizationRequestParameters = ();
pub type RequestUrl = ();
pub type Nickname = [u8; 0x21];
pub type SystemProgramIdentification = ();
pub type Uid = u128;
pub type ProfileDigest = u128;
pub type NetworkServiceAccountId = u64;
pub type CallbackUri = ();
pub type NintendoAccountId = u64;
