mod impl_io_auth_procedure_for_nintendo_account_linkage;
pub use self::impl_io_auth_procedure_for_nintendo_account_linkage::*;
mod impl_i_authorization_request;
pub use self::impl_i_authorization_request::*;
mod impl_io_auth_procedure_for_external_nsa;
pub use self::impl_io_auth_procedure_for_external_nsa::*;
pub type NasUserBase = ();
pub type NasUserBaseForApplication = ();
pub type State = ();
pub type NasClientInfo = ();
