[package]
authors = ["roblabla <unfiltered@roblab.la>"]
name = "megaton-allocator"
version = "0.1.0"

[dependencies]
spin = { version = "0.4.6" }
megaton-hammer = { path = "../megaton-hammer" }

linked_list_allocator = "0.6.2"
