mod impl_i_hid_debug_server;
pub use self::impl_i_hid_debug_server::*;
mod impl_i_hid_temporary_server;
pub use self::impl_i_hid_temporary_server::*;
mod impl_i_hid_system_server;
pub use self::impl_i_hid_system_server::*;
mod impl_i_hid_server;
pub use self::impl_i_hid_server::*;
mod impl_i_applet_resource;
pub use self::impl_i_applet_resource::*;
mod impl_i_active_vibration_device_list;
pub use self::impl_i_active_vibration_device_list::*;
pub mod system;
pub type BasicXpadId = u32;
pub type JoyXpadId = u32;
pub type VibrationValue = u128;
pub mod debug;
pub type SixAxisSensorHandle = u32;
pub mod tmp;
pub type VibrationDeviceHandle = u32;
pub type NpadStyleTag = u32;
pub type ConsoleSixAxisSensorHandle = u32;
pub type VibrationDeviceInfoForIpc = u64;
pub type TouchState = ();
