mod impl_IHidDebugServer;
pub use self::impl_IHidDebugServer::*;
mod impl_IAppletResource;
pub use self::impl_IAppletResource::*;
mod impl_IHidTemporaryServer;
pub use self::impl_IHidTemporaryServer::*;
mod impl_IHidSystemServer;
pub use self::impl_IHidSystemServer::*;
mod impl_IHidServer;
pub use self::impl_IHidServer::*;
mod impl_IActiveVibrationDeviceList;
pub use self::impl_IActiveVibrationDeviceList::*;
pub mod system;
pub type BasicXpadId = u32;
pub type JoyXpadId = u32;
pub type VibrationValue = u128;
pub mod debug;
pub type NpadStyleTag = u32;
pub type SixAxisSensorHandle = u32;
pub mod tmp;
pub type VibrationDeviceHandle = u32;
pub type ConsoleSixAxisSensorHandle = u32;
pub type VibrationDeviceInfoForIpc = u64;
pub type TouchState = ();
