mod impl_IServiceCreator;
pub use self::impl_IServiceCreator::*;
mod impl_INewlyArrivedEventHolder;
pub use self::impl_INewlyArrivedEventHolder::*;
mod impl_INewsService;
pub use self::impl_INewsService::*;
mod impl_IOverwriteEventHolder;
pub use self::impl_IOverwriteEventHolder::*;
mod impl_INewsDatabaseService;
pub use self::impl_INewsDatabaseService::*;
mod impl_INewsDataService;
pub use self::impl_INewsDataService::*;
