mod impl_IScreenShotService;
pub use self::impl_IScreenShotService::*;
mod impl_IAlbumAccessorService;
pub use self::impl_IAlbumAccessorService::*;
mod impl_IScreenShotApplicationService;
pub use self::impl_IScreenShotApplicationService::*;
mod impl_IAlbumControlService;
pub use self::impl_IAlbumControlService::*;
mod impl_IScreenShotControlService;
pub use self::impl_IScreenShotControlService::*;
