mod impl_i_ir_sensor_server;
pub use self::impl_i_ir_sensor_server::*;
mod impl_i_ir_sensor_system_server;
pub use self::impl_i_ir_sensor_system_server::*;
pub type PackedMcuVersion = u32;
pub type ImageTransferProcessorState = u128;
pub type IrCameraHandle = u32;
pub type PackedMomentProcessorConfig = [u8; 0x20];
pub type PackedImageTransferProcessorConfig = [u8; 0x18];
pub type PackedClusteringProcessorConfig = [u8; 0x28];
pub type PackedTeraPluginProcessorConfig = u64;
pub type PackedDpdProcessorConfig = [u8; 0xc];
